type shortTeamNamesType = {
	[key: string]: string
}

export const shortTeamNames: shortTeamNamesType = {
	'CSKA Moscow': 'CSKA',
	'Spartak Moscow': 'Spartak M',
	Zenit: 'Zenit',
	'Lokomotiv Moscow': 'Lokomotiv',
	Krasnodar: 'Krasnodar',
	'FK Rostov': 'FK Rostov',
	'Arsenal Tula': 'Arsenal T',
	Ufa: 'Ufa',
	'Krylya Sovetov': 'Krylya S',
	Orenburg: 'Orenburg',
	'Rubin Kazan': 'Rubin K',
	Ural: 'Ural',
	'Akhmat Grozny': 'Akhmat',
	'Dynamo Moscow': 'Dynamo M',
	Tambov: 'Tambov',
	Sochi: 'Sochi',
	Khimki: 'Khimki',
	'R. Volgograd': 'Rotor V',
	Enisey: 'Enisey',
	'Pari NN': 'Pari NN',
	'Fakel Voronezh': 'Fakel V',
	'Torpedo Moscow': 'Torpedo M',
	Baltika: 'Baltika',
	'Akron Togliatti': 'Akron T',
	'Dynamo Makhachkala': 'Makhachkala',
	Tomsk: 'Tomsk',
	'SKA Khabarovsk': 'SKA Khab.',
	Yenisey: 'Yenisey',
	'FK Saransk': 'Saransk',
	'Shinnik Yaroslavl': 'Shinnik',
	Neftekhimik: 'Neftekhimik',
	'Spartak Moscow 2': 'Spartak2',
	Luch: 'Luch',
	Kursk: 'Kursk',
	Armavir: 'Armavir',
	'Chertanovo M.': 'Chertanovo',
	'Krasnodar 2': 'Krasnodar2',
	'FK Chayka': 'Chayka',
	Tekstilshtik: 'Tekstilshtik',
	Omsk: 'Omsk',
	'Volgar-Astrakhan': 'Astrakhan V',
	'D. Bryansk': 'D. Bryansk',
	'Veles Moscow': 'Veles',
	'Alania 2': 'Alania2',
	'Alania Vladikavkaz': 'Alania V',
	'Olimp-Dolgoprudny': 'Dolgoprudny',
	Kamaz: 'Kamaz',
	Lipetsk: 'Lipetsk',
	Urozhay: 'Urozhay',
	'Rodina Moscow': 'Rodina',
	Ulyanovsk: '',
	Saratov: 'Ulyanovsk',
	Tyumen: 'Tyumen',
	'Chernomorets Novorossijsk': 'Chernomorets',
	Leningradets: 'Leningradets',
	Kuban: 'Kuban',
	'Manchester Utd': 'Man Utd',
	Newcastle: 'Newcastle',
	Bournemouth: 'Bournemouth',
	Watford: 'Watford',
	Wolves: 'Wolves',
	Liverpool: 'Liverpool',
	Southampton: 'Southampton',
	Arsenal: 'Arsenal',
	Burnley: 'Burnley',
	Everton: 'Everton',
	Leicester: 'Leicester',
	Tottenham: 'Tottenham',
	'West Ham': 'West Ham',
	Chelsea: 'Chelsea',
	'Manchester City': 'Man City',
	Brighton: 'Brighton',
	'Crystal Palace': 'Cr Palace',
	'Sheffield Utd': 'Sheffield U',
	'Aston Villa': 'Aston V',
	Norwich: 'Norwich',
	Fulham: 'Fulham',
	'West Brom': 'West Brom',
	Leeds: 'Leeds',
	Brentford: 'Brentford',
	Nottingham: 'Nottingham',
	Luton: 'Luton',
	Huddersfield: 'Huddersfield',
	Reading: 'Reading',
	Birmingham: 'Birmingham',
	'Bristol City': 'Bristol C',
	Millwall: 'Millwall',
	Preston: 'Preston',
	Wigan: 'Wigan',
	Hull: 'Hull',
	Blackburn: 'Blackburn',
	Derby: 'Derby',
	Middlesbrough: 'Middlesbrough',
	QPR: 'QPR',
	'Sheffield Wed': 'Sheffield W',
	Stoke: 'Stoke',
	Barnsley: 'Barnsley',
	Charlton: 'Charlton',
	Rotherham: 'Rotherham',
	Coventry: 'Coventry',
	Wycombe: 'Wycombe',
	Peterborough: 'Peterborough',
	Blackpool: 'Blackpool',
	Sunderland: 'Sunderland',
	Ipswich: 'Ipswich',
	Plymouth: 'Plymouth',
	'Oxford Utd': 'Oxford Utd',
	Portsmouth: 'Portsmouth',
	Swansea: 'Swansea',
	Cardiff: 'Cardiff',
	'Bayern Munich': 'Bayern M',
	Dusseldorf: 'Dusseldorf',
	'Hertha Berlin': 'Hertha',
	Freiburg: 'Freiburg',
	Wolfsburg: 'Wolfsburg',
	'Werder Bremen': 'Werder',
	'B. Monchengladbach': 'Borussia M',
	Mainz: 'Mainz',
	Dortmund: 'Dortmund',
	Hoffenheim: 'Hoffenheim',
	'Bayer Leverkusen': 'Bayer L',
	'Eintracht Frankfurt': 'Eintracht',
	Augsburg: 'Augsburg',
	'RB Leipzig': 'Leipzig',
	Schalke: 'Schalke',
	Heidenheim: 'Heidenheim',
	'Union Berlin': 'Un Berlin',
	Paderborn: 'Paderborn',
	'FC Koln': 'Koln',
	Stuttgart: 'Stuttgart',
	'Arminia Bielefeld': 'Arminia',
	'Holstein Kiel': 'Kiel',
	'Hamburger SV': 'Hamburger',
	Bochum: 'Bochum',
	'Greuther Furth': 'Furth',
	Darmstadt: 'Darmstadt',
	Hannover: 'Hannover',
	Nurnberg: 'Nurnberg',
	Regensburg: 'Regensburg',
	'SG Dynamo Dresden': 'D Dresden',
	Ingolstadt: 'Ingolstadt',
	'St. Pauli': 'St. Pauli',
	Sandhausen: 'Sandhausen',
	Aue: 'Aue',
	'Karlsruher SC': 'Karlsruher',
	Wehen: 'Wehen',
	'VfL Osnabruck': 'Osnabruck',
	Braunschweig: 'Braunschweig',
	'Wurzburger Kickers': 'W Kickers',
	Kaiserslautern: 'Kaiserslautern',
	'Hansa Rostock': 'Hansa R',
	Magdeburg: 'Magdeburg',
	Elversberg: 'Elversberg',
	'Preussen Munster': 'P Munster',
	Ulm: 'Ulm',
	Lazio: 'Lazio',
	Sassuolo: 'Sassuolo',
	'AC Milan': 'Milan',
	Cagliari: 'Cagliari',
	Napoli: 'Napoli',
	Spal: 'Spal',
	Udinese: 'Udinese',
	Genoa: 'Genoa',
	Juventus: 'Juventus',
	'AS Roma': 'Roma',
	Sampdoria: 'Sampdoria',
	Atalanta: 'Atalanta',
	Bologna: 'Bologna',
	Fiorentina: 'Fiorentina',
	Torino: 'Torino',
	Verona: 'Verona',
	Inter: 'Inter',
	Brescia: 'Brescia',
	Parma: 'Parma',
	Lecce: 'Lecce',
	Crotone: 'Crotone',
	Benevento: 'Benevento',
	Spezia: 'Spezia',
	Empoli: 'Empoli',
	Salernitana: 'Salernitana',
	Venezia: 'Venezia',
	Cremonese: 'Cremonese',
	Monza: 'Monza',
	Frosinone: 'Frosinone',
	Como: 'Como',
	Barcelona: 'Barcelona',
	'Atl. Madrid': 'At Madrid',
	'Ath Bilbao': 'At Bilbao',
	Valencia: 'Valencia',
	Villarreal: 'Villarreal',
	Sevilla: 'Sevilla',
	Leganes: 'Leganes',
	'Celta Vigo': 'Celta',
	Levante: 'Levante',
	Espanyol: 'Espanyol',
	'Real Madrid': 'Real M',
	Alaves: 'Alaves',
	Betis: 'Betis',
	Eibar: 'Eibar',
	Getafe: 'Getafe',
	'Real Sociedad': 'Real S',
	'Granada CF': 'Granada',
	Valladolid: 'Valladolid',
	Osasuna: 'Osasuna',
	Mallorca: 'Mallorca',
	'Cadiz CF': 'Cadiz',
	Huesca: 'Huesca',
	Elche: 'Elche',
	'Rayo Vallecano': 'Rayo V',
	Girona: 'Girona',
	Almeria: 'Almeria',
	'Las Palmas': 'L Palmas',
	Angers: 'Angers',
	Bordeaux: 'Bordeaux',
	Lille: 'Lille',
	Lyon: 'Lyon',
	Marseille: 'Marseille',
	Montpellier: 'Montpellier',
	Nantes: 'Nantes',
	Nice: 'Nice',
	PSG: 'PSG',
	Amiens: 'Amiens',
	Dijon: 'Dijon',
	Monaco: 'Monaco',
	Nimes: 'Nimes',
	Reims: 'Reims',
	Rennes: 'Rennes',
	Strasbourg: 'Strasbourg',
	Toulouse: 'Toulouse',
	Brest: 'Brest',
	Metz: 'Metz',
	'St Etienne': 'St Etienne',
	Lorient: 'Lorient',
	Lens: 'Lens',
	Clermont: 'Clermont',
	Auxerre: 'Auxerre',
	Troyes: 'Troyes',
	'AC Ajaccio': 'Ajaccio',
	'Le Havre': 'Havre',
	Benfica: 'Benfica',
	'FC Porto': 'Porto',
	Maritimo: 'Maritimo',
	Moreirense: 'Moreirense',
	Portimonense: 'Portimonense',
	Braga: 'Braga',
	Tondela: 'Tondela',
	'Vitoria Setubal': 'Vitoria S',
	Aves: 'Aves',
	BSAD: 'BSAD',
	Boavista: 'Boavista',
	'Vitoria Guimaraes': 'Vitoria G',
	'Rio Ave': 'Rio Ave',
	'Santa Clara': 'Santa Clara',
	'Sporting CP': 'Sporting',
	'Pacos Ferreira': 'Pacos Ferreira',
	Famalicao: 'Famalicao',
	'Gil Vicente': 'Gil Vicente',
	Nacional: 'Nacional',
	'SC Farense': 'Farense',
	Arouca: 'Arouca',
	Chaves: 'Chaves',
	Estoril: 'Estoril',
	Vizela: 'Vizela',
	'Casa Pia': 'Casa Pia',
	Estrela: 'Estrela',
	AVS: 'AVS',
}
